Feature/files upload management
MonsieurGourmand/interface pull request #14
Opened 2019-05-14 09:38 UTC by LiliceD

2019-05-15 13:50 UTC, TomYoYo requested changes

2019-05-15 13:50 UTC, TomYoYo commented on Model/ProductTechnicalForm.php
> +     * @var int
@var Product ?

2019-05-15 13:50 UTC, TomYoYo commented on Service/MGD.php
> +            $this->client->setAccessTokenType(Client::ACCESS_TOKEN_BEARER);
Pourquoi tu fais ça ? Les tokens sont déjà de type bearer normalement

2019-05-17 14:39 UTC, LiliceD commented on Service/MGD.php
> +            $this->client->setAccessTokenType(Client::ACCESS_TOKEN_BEARER);
Nope ils sont tout le temps dans l'URL (cf profiler). Mais je suis d'accord pour mettre par défaut de type bearer.

2019-05-17 14:40 UTC, LiliceD commented on Model/ProductTechnicalForm.php
> +     * @var int
Non je retourne que l'ID. Dans l'entité sur API il y a un accesseur getProductId et c'est lui qui est utilisé pour sérializer la donnée.

2019-05-17 14:51 UTC, LiliceD commented on Service/MGD.php
> +            $this->client->setAccessTokenType(Client::ACCESS_TOKEN_BEARER);
A la création d'un nouveau Client oauth la valeur par défaut du type d'access token c'était dans l'url et on ne modifiait cette valeur nulle part.
J'ai fait la modif sur la PR d'oauth2 mais j'espère que ça ne va pas tout casser x)
https://github.com/MonsieurGourmand/oauth2/pull/1

2019-05-22 15:10 UTC, merged